CREATE TABLE `horizons`
(
    `id`                  mediumint(9) NOT NULL,
    `article`             varchar(50) CHARACTER SET utf8   DEFAULT '',
    `channels`            varchar(200) CHARACTER SET utf8  DEFAULT '',
    `content`             varchar(1000) CHARACTER SET utf8 DEFAULT '',
    `content_more`        varchar(50) CHARACTER SET utf8   DEFAULT '',
    `content_text`        varchar(1000) CHARACTER SET utf8 DEFAULT '',
    `global_channel_name` varchar(50) CHARACTER SET utf8   DEFAULT '',
    `global_more_uri`     varchar(50) CHARACTER SET utf8   DEFAULT '',
    `display_time`        time                             DEFAULT NULL,
    `image_uris`          varchar(50) CHARACTER SET utf8   DEFAULT '',
    `is_calendar`         tinyint(4) DEFAULT '0',
    `is_favourite`        tinyint(4) DEFAULT '0',
    `is_priced`           tinyint(4) DEFAULT '0',
    `is_scaling`          tinyint(4) DEFAULT '0',
    `reference`           varchar(50) CHARACTER SET utf8   DEFAULT '0',
    `related_themes`      varchar(1000) CHARACTER SET utf8 DEFAULT '0',
    `score`               smallint(6) DEFAULT '0',
    `symbols`             varchar(50) CHARACTER SET utf8   DEFAULT '0',
    `tags`                varchar(50) CHARACTER SET utf8   DEFAULT '0',
    `title`               varchar(50) CHARACTER SET utf8   DEFAULT '0',
    `type`                varchar(50) CHARACTER SET utf8   DEFAULT '0',
    `gmt_created_time`    timestamp NOT NULL               DEFAULT CURRENT_TIMESTAMP,
    `gmt_update_time`     timestamp NOT NULL               DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8